nyt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.frontpage, name='frontpage'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('update/', views.update, name='update')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    api_key = models.CharField(max_length=32)


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    # post_save.connect(create_user_profile, sender='users.profile')

users/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from random import randint


class SignInForm(forms.ModelForm):
    a = randint(20,50)
    b = randint(1,20)
    summation=forms.IntegerField(label=f"{a} + {b} =", required=True, help_text="Proof you are not a robot.")

    class Meta:
        model = User
        fields = ('username', 'password', "summation")
        widgets = {
            'password': forms.PasswordInput(),
        }

    def verification(self):
        s = self.a + self.b
        return s


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["api_key"]
        widgets = {'api_key': forms.PasswordInput(),}

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import transaction
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from .models import Profile
from .forms import SignInForm, UserForm, ProfileForm

from pprint import pprint
import json
import requests

def register(request):
    '''Register a new user.'''
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('users:frontpage'))
    context = {'form': form}
    return render(request, 'register.html', context)


# def register(request):
#     '''Register a new user with api_key'''
#
#     if request.method != 'POST':
#         form = RegisterForm()
#     else:
#         form = RegisterForm(data=request.POST)
#         if form.is_valid():
#             new_user = form.save()
#             messages.success(request, f'Account has created for {new_user.username}!')
#             authenticated_user = authenticate(username=new_user.username,
#                                               password=request.POST['password1'])
#             login(request, authenticated_user)
#             if len(new_user.api_key) != 42:
#                 messages.info(request, "API key is not correct.")
#             return HttpResponseRedirect(reverse('users:profile'))
#     return render(request, 'register.html', {'form':form})


# def register_one2one(request):
#     if request.method == 'POST':
#         user_form = UserForm(request.POST)
#         profile_form = ProfileForm(request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             new_user=user_form.save()
#             # profile = profile_form.save(commit=False)
#             # profile.user = request.user
#             profile.save()
#
#             messages.success(request, 'Your profile was successfully created!')
#             authenticated_user = authenticate(username=new_user.username,
#                                               password=new_user.password)
#             login(request, authenticated_user)
#             return redirect('users:profile')
#         else:
#             messages.error(request, 'Please correct the error below.')
#     else:
#         user_form = UserForm()
#         profile_form = ProfileForm()
#     return render(request, 'register.html', {'user_form': user_form, 'profile_form': profile_form})


def logout_view(request):
    logout(request)
    return render(request, "frontpage.html")


def frontpage(request):
    form = SignInForm(request.POST or None )
    if request.method == 'POST' and form.is_valid:
        username = request.POST['username'] # form.cleaned_data["username"] ???
        password = request.POST['password']
        sum = request.POST["summation"]
        if form.verification() != int(sum):
            print(sum, form.verification())
            messages.warning(request, "Are you a robot that can't count?")
            # redirect("frontpage")
        else:
            authenticated_user = authenticate(username=username,
                                          password=password)
            try:
                login(request, authenticated_user)
                return HttpResponseRedirect(reverse("users:frontpage"))
            except AttributeError:
                messages.info(request, "Sorry, your username and password don't match.")
            except TypeError:
                messages.info(request, "Sorry, not working.Try again.")
    else:
        form = SignInForm()

    context = {"form": form}
    return render(request, 'frontpage.html', context)

@ login_required()
def profile(request):
    if len(request.user.profile.api_key) != 32:
        messages.warning(request, "Sorry, you don't have a valid API key. Please update your profile")
    else:
        sections = ['arts', 'automobiles', 'books', 'business', 'fashion', 'food', 'health', 'home',
                  'insider', 'magazine', 'movies', 'national', 'nyregion', 'obituaries', 'opinion',
                  'politics', 'realestate', 'science', 'sports', 'sundayreview', 'technology',
                  'theater', 'tmagazine', 'travel', 'upshot', 'world']
        ans="arts" # default session
        if request.method == 'POST':
            ans=request.POST.get("sections")
            messages.success(request, f"You have chosen {ans}. Here are the articles for you.")
        prof=Profile.objects.get(id=request.user.id)
        key=prof.api_key.strip()
        path = "https://api.nytimes.com/svc/topstories/v2/" + ans + ".json?api-key="+key
        download = requests.get(path).json()

        articles=[]
        for k, v in download.items():
            if k == "results":
                for l in v:
                    item = {}
                    for key, val in l.items():
                        if key in ["title", "abstract", "url"]:
                            item[key]=val
                    articles.append(item)

        context = {"sections": sections, "articles":articles}
    return render(request, "profile.html", context)


@login_required
@transaction.atomic
def update(request):
    if request.method == 'POST':
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=request.user.profile)
            if user_form.is_valid() and profile_form.is_valid():
                new_user=user_form.save()
                profile_form.save()
                messages.success(request, 'Your api key has been added!')
                return redirect('users:profile')
            else:
                messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'update.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def about(request):
    profile=Profile.objects.all()

    return render(request, "about.html", {"profile": profile})

users/templates/about.html
{% extends 'base.html' %}
{% block content%}
<br>
<div class="container">
<h5>{{user.username.title}}'s profile</h5>
</div>
<br>
{% if user.is_authenticated%}
    {% for p in profile.values %}
        {% if user.id == p.id %}
            <ul class="list-group">
              <li class="list-group-item"><span class="font-weight-light">First Name:</span> {{user.first_name.title}}</li>
              <li class="list-group-item"><span class="font-weight-light">Last Name:</span> {{user.last_name.title}}</li>
              <li class="list-group-item"><span class="font-weight-light">Email: </span> {{user.email}}</li>
              <li class="list-group-item"><span class="font-weight-light">API KEY: </span> {{p.api_key}}</li>
            </ul>

        {% endif %}
    {% endfor %}
{% endif %}

{% endblock%}

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
            <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

    <title>NYT articles</title>
</head>
<body>
      <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" style="color:white"href="{% url 'users:frontpage' %}">New York Times</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'users:about' %}">About</a>
                  <a class="nav-item nav-link" href="{% url 'users:update' %}">Update</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
                  <a class="nav-item nav-link" href="#"><strong>Hello, {{user.username}}!</strong></a>
                    {% else %}
                  <a class="nav-item nav-link" href="{% url 'users:frontpage' %}">Log in</a>
                  <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>

   <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}

            {% endblock %}
        </div>

      </div>
       <br>

       <foot>copyright @2019 Mingy</foot>
    </main>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

users/templates/frontpage.html
{% extends 'base.html' %}
{% block content%}

<br>
<div class="content-section">
{% if user.is_authenticated %}
    <h3>Welcome to this page, {{user.username.title}}!</h3>
    <br>
<p class="border-top mb-10">Now you can go read <a href="{% url 'users:profile' %}">NYT</a> top stories.</p>
{% else %}
    <h5>Please Log in first if you have an account. </h5>
    <br>
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form action="{% url 'users:frontpage' %}" method = "post">
        {%csrf_token%}
        {{form.as_p}}
        <button name="submit">Sign in</button>
    </form>
{% endif %}

</div>


{% endblock%}

users/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h5>Please sign in first. It only takes a few seconds. </h5>
    <br>
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form action="{% url 'users:login' %}" method = "get">
    {% csrf_token %}
    {{ form.as_p}}

    <button name="submit">Sign in</button>
    <input type="hidden" name="next" value="{% url 'users:frontpage'%}">

    </form>

{% endblock %}

users/templates/logout.html
{% extends "base.html" %}

{% block content %}
    <h5>You have signed out from the page </h5>


{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% block content%}

<div class="content-section">
{% if user.is_authenticated %}
    <legend class="border-bottom mb-4">
        <h3> Hello {{user.username.title}}! Welcome to Top Stories of NYT. </h3>
    </legend>
    <form class="form-inline" method="post"> {% csrf_token%}
        {% if user.profile.api_key %}
        <div class="col-md-6">
            <span class="align-text-bottom">
                Well done! You have a 32 digits API key with us.
            </span>
        </div>
        {% endif %}
        <div class="col-md-4">
            <select name="sections" class="custom-select">
                <option selected>Select the sections of your interest</option>
                  {% for s in sections %}
                    <option value="{{s}}">{{s}}</option>
                  {% endfor %}
            </select>
        </div>
        <div class="col-md-2">
            <input class="btn btn-secondary btn-lg" type="submit" value="Submit"/>

       </div>
    </form>
    <p class="border-top mb-8"><a href="{% url 'logout' %}"> - Log Out -</a></p>
{% endif %}
</div>

<div class="container">
    <div class="col-md-12">
    <table class="table table-striped">

    <thead>
      <tr>
        <th>Title</th>
        <th>Abstract</th>
        <th>URL</th>
      </tr>
    </thead>

    <tbody>
    {% for a_list in articles %}
        <tr>
            {% for k, v in a_list.items %}
            <td>
                {% if k == "url" %}
                    <a href="{{v}}">{{v}}</a>
                {% elif k == "abstract" %}
                    <span class="font-weight-light">{{v}}</span>
                {% else %}
                    <span class="font-italic">{{v}}</span>
                {% endif %}
            </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>

{% endblock%}

users/templates/register.html
{% extends 'base.html' %}
{% block content%}
<h4>Thank you for signing up a new account.</h4>
<br>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Register</button>
</form>


{% endblock%}

users/templates/update.html
{% extends 'base.html' %}
{% block content%}
<h4>Thank you for trusting us with your key.</h4>
<br>

<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Update your profile</button>
</form>


{% endblock%}